name: C:\Users\jared\miniconda3\envs\xarray-climate
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiobotocore=2.24.2=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py313hd650c13_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.10.0=pyhe01879c_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py313h5ea7bf4_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hd9a66b3_19
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.5=hccb7587_3
  - aws-c-http=0.10.4=h04b3cea_0
  - aws-c-io=0.21.2=h20b9e97_1
  - aws-c-mqtt=0.13.3=h6b158f5_3
  - aws-c-s3=0.8.6=h46905be_2
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.33.1=h89ba1a2_2
  - aws-sdk-cpp=1.11.606=h14334ec_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - botocore=1.40.18=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py313hfe59770_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.8.3=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - cartopy=0.25.0=py313hc90dcd4_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313h5ea7bf4_1
  - cftime=1.6.4=py313h0591002_2
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hf069bd2_2
  - cpython=3.13.7=py313hd8ed1ab_100
  - crc32c=2.7.1=py313h5fd188c_2
  - cryptography=46.0.1=py313h392ebe0_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py313ha7868ed_0
  - dask=2025.9.0=pyhcf101f3_0
  - dask-core=2025.9.0=pyhcf101f3_0
  - debugpy=1.8.16=py313h927ade5_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2025.9.0=pyhcf101f3_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py313hd650c13_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py313h0c48a3b_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gcsfs=2025.9.0=pyhd8ed1ab_0
  - geos=3.13.1=h9ea8674_0
  - google-api-core=2.25.1=pyhd8ed1ab_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.2=pyhd8ed1ab_0
  - google-cloud-core=2.4.3=pyhd8ed1ab_0
  - google-cloud-storage=3.4.0=pyhd8ed1ab_0
  - google-crc32c=1.7.1=py313h5327936_1
  - google-resumable-media=2.7.2=pyhd8ed1ab_2
  - googleapis-common-protos=1.70.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - grpcio=1.73.1=py313h3c83859_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.6.4=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py313hf7f959b_101
  - harfbuzz=11.5.0=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intake=2.0.8=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.5.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py313hfa70ccb_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.9=py313h1a38498_1
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libarrow=21.0.0=hb0fdb7d_3_cpu
  - libarrow-acero=21.0.0=h7d8d6a5_3_cpu
  - libarrow-compute=21.0.0=h2db994a_3_cpu
  - libarrow-dataset=21.0.0=h7d8d6a5_3_cpu
  - libarrow-substrait=21.0.0=hf865cc0_3_cpu
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.1=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.1.0=h1383e82_5
  - libglib=2.86.0=h5f26cbf_0
  - libgomp=15.1.0=h1383e82_5
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h04afb49_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libnetcdf=4.9.3=nompi_ha45073a_102
  - libparquet=21.0.0=h24c48c9_3_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - libre2-11=2025.08.12=h0eb2380_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=h550210a_6
  - libutf8proc=2.11.0=h0b34c2f_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=hfa2b4ca_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py313ha07860f_1
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.2=py313hb4c8b1a_1
  - matplotlib=3.10.6=py313hfa70ccb_1
  - matplotlib-base=3.10.6=py313he1ded55_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.1.1=py313hf069bd2_1
  - multidict=6.6.3=py313hd650c13_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.5.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py313hbe59507_104
  - networkx=3.5=pyhe01879c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numcodecs=0.16.1=py313hc90dcd4_1
  - numpy=2.3.3=py313hce7ae62_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.3=h725018a_0
  - orc=2.2.0=h0018cbe_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py313hc90dcd4_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313h641beac_2
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - proj=9.7.0=h9080b7b_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313hb4c8b1a_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=6.31.1=py313h16c7a9f_0
  - psutil=7.0.0=py313h5ea7bf4_1
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py313hfa70ccb_0
  - pyarrow-core=21.0.0=py313h5921983_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.2.4=pyhcf101f3_0
  - pyproj=3.7.2=py313h24787ba_2
  - pyshp=3.0.1=pyhd8ed1ab_0
  - pyside6=6.9.2=py313hd8d090c_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.7=hdf00ec1_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.7=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py313h40c08fc_1
  - pywinpty=2.0.15=py313h5813708_0
  - pyyaml=6.0.2=py313hb4c8b1a_2
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.2=ha0de62e_2
  - re2=2025.08.12=ha104f34_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py313hfbe8231_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - s3fs=2025.9.0=pyhd8ed1ab_0
  - scipy=1.16.2=py313h62a08ca_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py313hd420520_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.4=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h18a62a1_3
  - tblib=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhe01879c_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py313h5ea7bf4_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py313h5ea7bf4_1
  - xarray=2025.9.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.20.1=py313hb4c8b1a_0
  - zarr=3.1.2=pyhcf101f3_0
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.25.0=py313h5fd188c_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - cfgrib==0.9.15.1
      - eccodes==2.44.0
      - eofs==2.0.0
      - findlibs==0.1.2
      - h5pyd==0.23.0
      - ipywidgets==8.1.7
      - joblib==1.5.2
      - jupyterlab-widgets==3.0.15
      - llvmlite==0.45.1
      - numba==0.62.1
      - requests-unixsocket==0.4.1
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - shap==0.50.0
      - slicer==0.0.8
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - utils==1.0.2
      - widgetsnbextension==4.0.14
prefix: C:\Users\jared\miniconda3\envs\xarray-climate
